name: boutique
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.10.4

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8
  gsheets: ^0.5.0
  image_picker: ^1.2.3
  intl: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

# Configuración del paquete para generar el ícono/logo de la app
flutter_launcher_icons:
  image_path: "assets/logo.png"
  windows:
    generate: true
    icon_size: 256
  android: true
  ios: true

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is included with your application.
  uses-material-design: true

  # Declaración de la carpeta de imágenes/assets
  assets:
    - assets/
    - assets/logo.png